"""sprint7_remisiones_lineas_oc

Revision ID: 00c43c0b91d0
Revises: 20a1155c2542
Create Date: 2026-05-04 01:53:23.081178
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00c43c0b91d0'
down_revision: Union[str, None] = '20a1155c2542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend movimiento_tipo enum with Sprint 7 values
    # (Postgres autogenerate doesn't detect added enum values).
    conn = op.get_bind()
    for new_val in (
        "ENTRADA_COMPRA",
        "SALIDA_REMISION",
        "CONFIRMACION_FACTURA",
        "CANCELACION_REMISION",
    ):
        conn.exec_driver_sql(
            f"ALTER TYPE movimiento_tipo ADD VALUE IF NOT EXISTS '{new_val}'"
        )
    # Extend oc_estado with RECIBIDA_PARCIAL
    conn.exec_driver_sql(
        "ALTER TYPE oc_estado ADD VALUE IF NOT EXISTS 'RECIBIDA_PARCIAL'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_orden_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('orden_compra_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('presentacion', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['ordenes_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_orden_compra_tenant_id'), 'lineas_orden_compra', ['tenant_id'], unique=False)
    op.create_index('ix_loc_orden', 'lineas_orden_compra', ['orden_compra_id'], unique=False)
    op.create_index('ix_loc_producto', 'lineas_orden_compra', ['producto_id'], unique=False)
    op.create_table('remisiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('unidad_entrega_id', sa.UUID(), nullable=True),
    sa.Column('almacen_origen_id', sa.UUID(), nullable=True),
    sa.Column('fecha_generada', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_facturada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('GENERADA', 'EN_TRANSITO', 'ENTREGADA', 'CONFIRMADA', 'FACTURADA', 'CANCELADA', name='remision_estado'), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iva_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_origen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unidad_entrega_id'], ['unidades_entrega.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'folio', name='uq_remision_folio')
    )
    op.create_index('ix_remision_cliente', 'remisiones', ['cliente_id'], unique=False)
    op.create_index('ix_remision_estado', 'remisiones', ['estado'], unique=False)
    op.create_index('ix_remision_pedido', 'remisiones', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_remisiones_almacen_origen_id'), 'remisiones', ['almacen_origen_id'], unique=False)
    op.create_index(op.f('ix_remisiones_cliente_id'), 'remisiones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_remisiones_factura_id'), 'remisiones', ['factura_id'], unique=False)
    op.create_index(op.f('ix_remisiones_pedido_id'), 'remisiones', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_remisiones_tenant_id'), 'remisiones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_remisiones_unidad_entrega_id'), 'remisiones', ['unidad_entrega_id'], unique=False)
    op.create_table('lineas_remision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('remision_id', sa.UUID(), nullable=False),
    sa.Column('linea_pedido_id', sa.UUID(), nullable=True),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('lote_inventario_id', sa.UUID(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_entregada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_facturada', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('presentacion', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('motivo_ajuste', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linea_pedido_id'], ['lineas_pedido.id'], ),
    sa.ForeignKeyConstraint(['lote_inventario_id'], ['lotes_inventario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['remision_id'], ['remisiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_linea_remision_producto', 'lineas_remision', ['producto_id'], unique=False)
    op.create_index('ix_linea_remision_remision', 'lineas_remision', ['remision_id'], unique=False)
    op.create_index(op.f('ix_lineas_remision_tenant_id'), 'lineas_remision', ['tenant_id'], unique=False)
    op.create_table('ajustes_remision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('remision_id', sa.UUID(), nullable=False),
    sa.Column('linea_remision_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('PESO', 'CANTIDAD', 'CANCELACION', 'SUSTITUCION', 'PRECIO', name='ajuste_remision_tipo'), nullable=False),
    sa.Column('cantidad_anterior', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cantidad_nueva', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('precio_anterior', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('precio_nuevo', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('producto_anterior_id', sa.UUID(), nullable=True),
    sa.Column('producto_nuevo_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('requiere_aprobacion', sa.String(length=10), nullable=True),
    sa.Column('aprobado_por', sa.UUID(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linea_remision_id'], ['lineas_remision.id'], ),
    sa.ForeignKeyConstraint(['producto_anterior_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['producto_nuevo_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['remision_id'], ['remisiones.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ajuste_remision', 'ajustes_remision', ['remision_id'], unique=False)
    op.create_index(op.f('ix_ajustes_remision_tenant_id'), 'ajustes_remision', ['tenant_id'], unique=False)
    op.add_column('lotes_inventario', sa.Column('cantidad_reservada', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False))
    op.add_column('lotes_inventario', sa.Column('orden_compra_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lotes_inventario', 'ordenes_compra', ['orden_compra_id'], ['id'])
    op.add_column('ordenes_compra', sa.Column('almacen_destino_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('fecha_entrega_esperada', sa.Date(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('fecha_recibida', sa.Date(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('ordenes_compra', sa.Column('iva_total', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('ordenes_compra', sa.Column('total_recibido', sa.Numeric(precision=18, scale=4), nullable=True))
    op.create_index('ix_oc_estado', 'ordenes_compra', ['estado'], unique=False)
    op.create_index('ix_oc_proveedor', 'ordenes_compra', ['proveedor_id'], unique=False)
    op.create_foreign_key(None, 'ordenes_compra', 'almacenes', ['almacen_destino_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordenes_compra', type_='foreignkey')
    op.drop_index('ix_oc_proveedor', table_name='ordenes_compra')
    op.drop_index('ix_oc_estado', table_name='ordenes_compra')
    op.drop_column('ordenes_compra', 'total_recibido')
    op.drop_column('ordenes_compra', 'iva_total')
    op.drop_column('ordenes_compra', 'subtotal')
    op.drop_column('ordenes_compra', 'fecha_recibida')
    op.drop_column('ordenes_compra', 'fecha_entrega_esperada')
    op.drop_column('ordenes_compra', 'almacen_destino_id')
    op.drop_constraint(None, 'lotes_inventario', type_='foreignkey')
    op.drop_column('lotes_inventario', 'orden_compra_id')
    op.drop_column('lotes_inventario', 'cantidad_reservada')
    op.drop_index(op.f('ix_ajustes_remision_tenant_id'), table_name='ajustes_remision')
    op.drop_index('ix_ajuste_remision', table_name='ajustes_remision')
    op.drop_table('ajustes_remision')
    op.drop_index(op.f('ix_lineas_remision_tenant_id'), table_name='lineas_remision')
    op.drop_index('ix_linea_remision_remision', table_name='lineas_remision')
    op.drop_index('ix_linea_remision_producto', table_name='lineas_remision')
    op.drop_table('lineas_remision')
    op.drop_index(op.f('ix_remisiones_unidad_entrega_id'), table_name='remisiones')
    op.drop_index(op.f('ix_remisiones_tenant_id'), table_name='remisiones')
    op.drop_index(op.f('ix_remisiones_pedido_id'), table_name='remisiones')
    op.drop_index(op.f('ix_remisiones_factura_id'), table_name='remisiones')
    op.drop_index(op.f('ix_remisiones_cliente_id'), table_name='remisiones')
    op.drop_index(op.f('ix_remisiones_almacen_origen_id'), table_name='remisiones')
    op.drop_index('ix_remision_pedido', table_name='remisiones')
    op.drop_index('ix_remision_estado', table_name='remisiones')
    op.drop_index('ix_remision_cliente', table_name='remisiones')
    op.drop_table('remisiones')
    op.drop_index('ix_loc_producto', table_name='lineas_orden_compra')
    op.drop_index('ix_loc_orden', table_name='lineas_orden_compra')
    op.drop_index(op.f('ix_lineas_orden_compra_tenant_id'), table_name='lineas_orden_compra')
    op.drop_table('lineas_orden_compra')
    # ### end Alembic commands ###
