"""initial schema

Revision ID: 040714f52a8f
Revises: 
Create Date: 2026-05-03 01:07:27.667639
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '040714f52a8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_codigos_postales',
    sa.Column('cp', sa.String(length=5), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('zona_horaria', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cp')
    )
    op.create_table('sat_formas_pago',
    sa.Column('clave', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sat_metodos_pago',
    sa.Column('clave', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sat_productos_servicios',
    sa.Column('clave', sa.String(length=8), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=8), nullable=True),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sat_regimenes',
    sa.Column('clave', sa.String(length=4), nullable=False),
    sa.Column('descripcion', sa.String(length=254), nullable=False),
    sa.Column('aplica_fisica', sa.String(length=2), nullable=True),
    sa.Column('aplica_moral', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sat_unidades',
    sa.Column('clave', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('simbolo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sat_usos_cfdi',
    sa.Column('clave', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=254), nullable=False),
    sa.Column('aplica_fisica', sa.String(length=2), nullable=True),
    sa.Column('aplica_moral', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_tenant_id', sa.UUID(), nullable=True),
    sa.Column('tier', sa.Enum('PRINCIPAL', 'SUB', 'SUB_SUB', name='tenant_tier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'SUSPENDED', 'CHURNED', name='tenant_status'), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=254), nullable=False),
    sa.Column('trade_name', sa.String(length=254), nullable=True),
    sa.Column('rfc', sa.String(length=15), nullable=False),
    sa.Column('regimen_fiscal_sat', sa.String(length=4), nullable=False),
    sa.Column('domicilio_fiscal_cp', sa.String(length=5), nullable=False),
    sa.Column('domicilio_fiscal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('seats_limit', sa.Integer(), nullable=True),
    sa.Column('trial_ends_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tenants_parent_tenant_id'), 'tenants', ['parent_tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('auth_user_id', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('almacenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('es_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo')
    )
    op.create_index(op.f('ix_almacenes_tenant_id'), 'almacenes', ['tenant_id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True),
    sa.Column('contratante', sa.String(length=254), nullable=False),
    sa.Column('contratante_rfc', sa.String(length=15), nullable=True),
    sa.Column('estado_mx', sa.String(length=50), nullable=True),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('monto_max', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_tenant_id'), 'contratos', ['tenant_id'], unique=False)
    op.create_table('csds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('numero_serie', sa.String(length=20), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('password_kms_id', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index(op.f('ix_csds_tenant_id'), 'csds', ['tenant_id'], unique=False)
    op.create_table('events_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_entity_id'), 'events_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_log_entity_type'), 'events_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_log_tenant_id'), 'events_log', ['tenant_id'], unique=False)
    op.create_table('listas_precios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo')
    )
    op.create_index(op.f('ix_listas_precios_tenant_id'), 'listas_precios', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('mensajes_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.Enum('WHATSAPP', 'EMAIL', 'WEB', 'SMS', 'API', name='mensaje_canal'), nullable=False),
    sa.Column('direccion', sa.Enum('IN', 'OUT', name='mensaje_direccion'), nullable=False),
    sa.Column('contraparte', sa.String(length=254), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_log_contraparte'), 'mensajes_log', ['contraparte'], unique=False)
    op.create_index(op.f('ix_mensajes_log_created_at'), 'mensajes_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_mensajes_log_tenant_id'), 'mensajes_log', ['tenant_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sku_interno', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=254), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('lote_default', sa.Integer(), nullable=True),
    sa.Column('clave_sat', sa.String(length=8), nullable=False),
    sa.Column('unidad_sat', sa.String(length=3), nullable=False),
    sa.Column('objeto_imp', sa.String(length=2), nullable=True),
    sa.Column('iva_tasa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ieps_tasa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('presentaciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('presentacion_default', sa.String(length=20), nullable=True),
    sa.Column('sinonimos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('aliases_clientes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('costo_promedio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku_interno')
    )
    op.create_index(op.f('ix_productos_nombre_normalizado'), 'productos', ['nombre_normalizado'], unique=False)
    op.create_index(op.f('ix_productos_tenant_id'), 'productos', ['tenant_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('rfc', sa.String(length=15), nullable=True),
    sa.Column('contacto', sa.String(length=254), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('categorias', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('contratos_lotes_atendidos', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo')
    )
    op.create_index(op.f('ix_proveedores_tenant_id'), 'proveedores', ['tenant_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('PRINCIPAL_GOV', 'SUB', 'PRIVADO', 'OTRO', name='cliente_tipo'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('legal_name', sa.String(length=254), nullable=False),
    sa.Column('rfc', sa.String(length=15), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=4), nullable=True),
    sa.Column('uso_cfdi_default', sa.String(length=5), nullable=True),
    sa.Column('forma_pago_default', sa.String(length=5), nullable=True),
    sa.Column('metodo_pago_default', sa.String(length=5), nullable=True),
    sa.Column('domicilio_fiscal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lista_precios_id', sa.UUID(), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=50), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('descuento_default', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('config_addenda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saldo_actual', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ventas_ytd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ultima_venta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_pago_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lista_precios_id'], ['listas_precios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo')
    )
    op.create_index(op.f('ix_clientes_rfc'), 'clientes', ['rfc'], unique=False)
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('contratos_lotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('numero_lote', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=254), nullable=False),
    sa.Column('asignado_a_tenant', sa.UUID(), nullable=True),
    sa.Column('lista_precios_id', sa.UUID(), nullable=True),
    sa.Column('monto_lote', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_tenant'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lista_precios_id'], ['listas_precios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'numero_lote')
    )
    op.create_index(op.f('ix_contratos_lotes_asignado_a_tenant'), 'contratos_lotes', ['asignado_a_tenant'], unique=False)
    op.create_table('lotes_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('almacen_id', sa.UUID(), nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('cantidad_inicial', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_inventario_almacen_id'), 'lotes_inventario', ['almacen_id'], unique=False)
    op.create_index(op.f('ix_lotes_inventario_fecha_caducidad'), 'lotes_inventario', ['fecha_caducidad'], unique=False)
    op.create_index(op.f('ix_lotes_inventario_producto_id'), 'lotes_inventario', ['producto_id'], unique=False)
    op.create_index(op.f('ix_lotes_inventario_tenant_id'), 'lotes_inventario', ['tenant_id'], unique=False)
    op.create_table('precios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lista_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('presentacion', sa.String(length=20), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_precios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lista_id', 'producto_id', 'presentacion', 'vigencia_desde')
    )
    op.create_index(op.f('ix_precios_lista_id'), 'precios', ['lista_id'], unique=False)
    op.create_index(op.f('ix_precios_producto_id'), 'precios', ['producto_id'], unique=False)
    op.create_table('unidades_entrega',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('tipo', sa.Enum('HOSPITAL', 'COMEDOR', 'ESCUELA', 'MILITAR', 'RECLUSORIO', 'ALMACEN', 'OTRO', name='unidad_tipo'), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado_mx', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('cp', sa.String(length=5), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=254), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto_email', sa.String(length=254), nullable=True),
    sa.Column('geo_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('frecuencia_entrega', sa.String(length=50), nullable=True),
    sa.Column('hora_corte_pedido', sa.Time(), nullable=True),
    sa.Column('hora_entrega', sa.Time(), nullable=True),
    sa.Column('protocolo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_entrega_contrato_id'), 'unidades_entrega', ['contrato_id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', 'MERMA', 'TRANSFERENCIA', name='movimiento_tipo'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ref_tipo', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.String(length=254), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_inventario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_lote_id'), 'movimientos_inventario', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_ref_id'), 'movimientos_inventario', ['ref_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_tenant_id'), 'movimientos_inventario', ['tenant_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('folio_interno', sa.String(length=20), nullable=True),
    sa.Column('contrato_lote_id', sa.UUID(), nullable=True),
    sa.Column('cliente_facturacion_id', sa.UUID(), nullable=False),
    sa.Column('unidad_entrega_id', sa.UUID(), nullable=True),
    sa.Column('fecha_pedido', sa.Date(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'CONFIRMADO', 'EN_SURTIDO', 'ENVIADO', 'ENTREGADO', 'FACTURADO', 'CANCELADO', name='pedido_estado'), nullable=False),
    sa.Column('canal', sa.Enum('WHATSAPP', 'EMAIL', 'EXCEL_BD', 'LIBRETA_FOTO', 'VOZ', 'WEB', 'API', 'MANUAL', name='canal_origen'), nullable=False),
    sa.Column('raw_message_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iva', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_facturacion_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_lote_id'], ['contratos_lotes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raw_message_id'], ['mensajes_log.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unidad_entrega_id'], ['unidades_entrega.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_facturacion_id'), 'pedidos', ['cliente_facturacion_id'], unique=False)
    op.create_index(op.f('ix_pedidos_contrato_lote_id'), 'pedidos', ['contrato_lote_id'], unique=False)
    op.create_index(op.f('ix_pedidos_fecha_pedido'), 'pedidos', ['fecha_pedido'], unique=False)
    op.create_index(op.f('ix_pedidos_folio_interno'), 'pedidos', ['folio_interno'], unique=False)
    op.create_index(op.f('ix_pedidos_requires_review'), 'pedidos', ['requires_review'], unique=False)
    op.create_index(op.f('ix_pedidos_tenant_id'), 'pedidos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pedidos_unidad_entrega_id'), 'pedidos', ['unidad_entrega_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('folio', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', 'TRASLADO', 'NOMINA', 'PAGO', name='factura_tipo'), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'TIMBRADA', 'CANCELADA', 'ERROR_TIMBRADO', name='factura_estado'), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('receptor_rfc', sa.String(length=15), nullable=False),
    sa.Column('receptor_nombre', sa.String(length=254), nullable=False),
    sa.Column('receptor_regimen', sa.String(length=4), nullable=False),
    sa.Column('receptor_uso_cfdi', sa.String(length=5), nullable=False),
    sa.Column('receptor_cp', sa.String(length=5), nullable=False),
    sa.Column('forma_pago', sa.String(length=5), nullable=True),
    sa.Column('metodo_pago', sa.String(length=5), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iva_trasladado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iva_retenido', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('isr_retenido', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uuid_sat', sa.UUID(), nullable=True),
    sa.Column('fecha_timbrado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pac', sa.String(length=50), nullable=True),
    sa.Column('xml_storage_path', sa.Text(), nullable=True),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('certificado_sat', sa.String(length=20), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=2), nullable=True),
    sa.Column('uuid_sustitucion', sa.UUID(), nullable=True),
    sa.Column('acuse_cancelacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addenda_xml', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'serie', 'folio', 'tipo')
    )
    op.create_index(op.f('ix_facturas_cliente_id'), 'facturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_facturas_pedido_id'), 'facturas', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_facturas_tenant_id'), 'facturas', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_facturas_uuid_sat'), 'facturas', ['uuid_sat'], unique=True)
    op.create_table('lineas_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('numero_linea', sa.SmallInteger(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=True),
    sa.Column('presentacion', sa.String(length=20), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_surtida', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=True),
    sa.Column('texto_original', sa.Text(), nullable=True),
    sa.Column('ai_match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_inventario.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', 'numero_linea')
    )
    op.create_index(op.f('ix_lineas_pedido_pedido_id'), 'lineas_pedido', ['pedido_id'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=True),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('pedido_origen_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADA', 'ACEPTADA', 'EN_TRANSITO', 'RECIBIDA', 'CANCELADA', name='oc_estado'), nullable=True),
    sa.Column('total_estimado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_origen_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_compra_pedido_origen_id'), 'ordenes_compra', ['pedido_origen_id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_proveedor_id'), 'ordenes_compra', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_tenant_id'), 'ordenes_compra', ['tenant_id'], unique=False)
    op.create_table('lineas_factura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('linea_pedido_id', sa.UUID(), nullable=True),
    sa.Column('numero_linea', sa.SmallInteger(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=True),
    sa.Column('clave_sat', sa.String(length=8), nullable=False),
    sa.Column('unidad_sat', sa.String(length=3), nullable=False),
    sa.Column('objeto_imp', sa.String(length=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unidad_descripcion', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('iva_tasa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('iva_importe', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_linea', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linea_pedido_id'], ['lineas_pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', 'numero_linea')
    )
    op.create_index(op.f('ix_lineas_factura_factura_id'), 'lineas_factura', ['factura_id'], unique=False)
    op.create_table('mermas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('motivo', sa.Enum('CADUCIDAD', 'CALIDAD', 'DEVOLUCION_CLIENTE', 'ROBO', 'DESCOMPOSICION', 'OTRO', name='merma_motivo'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('factura_id', sa.UUID(), nullable=True),
    sa.Column('evidencia_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_inventario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mermas_tenant_id'), 'mermas', ['tenant_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('forma_pago', sa.String(length=5), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('factura_pago_id', sa.UUID(), nullable=True),
    sa.Column('uuid_complemento', sa.UUID(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factura_pago_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_cliente_id'), 'pagos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pagos_tenant_id'), 'pagos', ['tenant_id'], unique=False)
    op.create_table('abonos_factura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('numero_parcialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id', 'factura_id', 'numero_parcialidad')
    )
    op.create_index(op.f('ix_abonos_factura_factura_id'), 'abonos_factura', ['factura_id'], unique=False)
    op.create_index(op.f('ix_abonos_factura_pago_id'), 'abonos_factura', ['pago_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonos_factura_pago_id'), table_name='abonos_factura')
    op.drop_index(op.f('ix_abonos_factura_factura_id'), table_name='abonos_factura')
    op.drop_table('abonos_factura')
    op.drop_index(op.f('ix_pagos_tenant_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_cliente_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_mermas_tenant_id'), table_name='mermas')
    op.drop_table('mermas')
    op.drop_index(op.f('ix_lineas_factura_factura_id'), table_name='lineas_factura')
    op.drop_table('lineas_factura')
    op.drop_index(op.f('ix_ordenes_compra_tenant_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_proveedor_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_pedido_origen_id'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_lineas_pedido_pedido_id'), table_name='lineas_pedido')
    op.drop_table('lineas_pedido')
    op.drop_index(op.f('ix_facturas_uuid_sat'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_tenant_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_pedido_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_pedidos_unidad_entrega_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_tenant_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_requires_review'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_folio_interno'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_fecha_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_contrato_lote_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_facturacion_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_movimientos_inventario_tenant_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_ref_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_lote_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_unidades_entrega_contrato_id'), table_name='unidades_entrega')
    op.drop_table('unidades_entrega')
    op.drop_index(op.f('ix_precios_producto_id'), table_name='precios')
    op.drop_index(op.f('ix_precios_lista_id'), table_name='precios')
    op.drop_table('precios')
    op.drop_index(op.f('ix_lotes_inventario_tenant_id'), table_name='lotes_inventario')
    op.drop_index(op.f('ix_lotes_inventario_producto_id'), table_name='lotes_inventario')
    op.drop_index(op.f('ix_lotes_inventario_fecha_caducidad'), table_name='lotes_inventario')
    op.drop_index(op.f('ix_lotes_inventario_almacen_id'), table_name='lotes_inventario')
    op.drop_table('lotes_inventario')
    op.drop_index(op.f('ix_contratos_lotes_asignado_a_tenant'), table_name='contratos_lotes')
    op.drop_table('contratos_lotes')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_rfc'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_proveedores_tenant_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_productos_tenant_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre_normalizado'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_mensajes_log_tenant_id'), table_name='mensajes_log')
    op.drop_index(op.f('ix_mensajes_log_created_at'), table_name='mensajes_log')
    op.drop_index(op.f('ix_mensajes_log_contraparte'), table_name='mensajes_log')
    op.drop_table('mensajes_log')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_listas_precios_tenant_id'), table_name='listas_precios')
    op.drop_table('listas_precios')
    op.drop_index(op.f('ix_events_log_tenant_id'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_entity_type'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_entity_id'), table_name='events_log')
    op.drop_table('events_log')
    op.drop_index(op.f('ix_csds_tenant_id'), table_name='csds')
    op.drop_table('csds')
    op.drop_index(op.f('ix_contratos_tenant_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_almacenes_tenant_id'), table_name='almacenes')
    op.drop_table('almacenes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_parent_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('sat_usos_cfdi')
    op.drop_table('sat_unidades')
    op.drop_table('sat_regimenes')
    op.drop_table('sat_productos_servicios')
    op.drop_table('sat_metodos_pago')
    op.drop_table('sat_formas_pago')
    op.drop_table('sat_codigos_postales')
    # ### end Alembic commands ###
