"""sprint10_chat_conversaciones_mensajes

Revision ID: fbb960a34d25
Revises: f87b2133aeaf
Create Date: 2026-05-04 09:26:53.061707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fbb960a34d25'
down_revision: Union[str, None] = 'f87b2133aeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=254), nullable=False),
    sa.Column('archivada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mensajes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('costo_usd', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes_whatsapp.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_conv_agente', 'chat_conversaciones', ['agente_id'], unique=False)
    op.create_index('ix_chat_conv_tenant', 'chat_conversaciones', ['tenant_id'], unique=False)
    op.create_index('ix_chat_conv_user', 'chat_conversaciones', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversaciones_tenant_id'), 'chat_conversaciones', ['tenant_id'], unique=False)
    op.create_table('chat_mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('adjuntos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=True),
    sa.Column('accion_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accion_resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_mensajes_tenant_id'), 'chat_mensajes', ['tenant_id'], unique=False)
    op.create_index('ix_chat_msg_conversacion', 'chat_mensajes', ['conversacion_id'], unique=False)
    op.create_index('ix_chat_msg_role', 'chat_mensajes', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_msg_role', table_name='chat_mensajes')
    op.drop_index('ix_chat_msg_conversacion', table_name='chat_mensajes')
    op.drop_index(op.f('ix_chat_mensajes_tenant_id'), table_name='chat_mensajes')
    op.drop_table('chat_mensajes')
    op.drop_index(op.f('ix_chat_conversaciones_tenant_id'), table_name='chat_conversaciones')
    op.drop_index('ix_chat_conv_user', table_name='chat_conversaciones')
    op.drop_index('ix_chat_conv_tenant', table_name='chat_conversaciones')
    op.drop_index('ix_chat_conv_agente', table_name='chat_conversaciones')
    op.drop_table('chat_conversaciones')
    # ### end Alembic commands ###
