"""sprint13_audit_log_base_maestra_runs

Revision ID: 6bb1b1d66a26
Revises: fbb960a34d25
Create Date: 2026-05-04 14:34:56.985948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6bb1b1d66a26'
down_revision: Union[str, None] = 'fbb960a34d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_maestra_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('semana_label', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('source_folder', sa.Text(), nullable=True),
    sa.Column('archivos_count', sa.Integer(), nullable=False),
    sa.Column('hospitales_ok', sa.Integer(), nullable=True),
    sa.Column('hospitales_warning', sa.Integer(), nullable=True),
    sa.Column('hospitales_fallidos', sa.Integer(), nullable=True),
    sa.Column('filas_bd', sa.Integer(), nullable=True),
    sa.Column('productos_no_match', sa.Integer(), nullable=True),
    sa.Column('output_local_path', sa.Text(), nullable=True),
    sa.Column('output_drive_url', sa.Text(), nullable=True),
    sa.Column('output_size_bytes', sa.Integer(), nullable=True),
    sa.Column('diff_pct_vs_anterior', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('ai_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('ai_validation_notes', sa.Text(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('conversacion_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_maestra_runs_tenant_id'), 'base_maestra_runs', ['tenant_id'], unique=False)
    op.create_index('ix_bm_runs_fecha', 'base_maestra_runs', ['fecha_inicio'], unique=False)
    op.create_index('ix_bm_runs_tenant', 'base_maestra_runs', ['tenant_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('ref_tipo', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('conversacion_id', sa.UUID(), nullable=True),
    sa.Column('mensaje_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ),
    sa.ForeignKeyConstraint(['mensaje_id'], ['chat_mensajes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_decisions_created', 'ai_decisions', ['created_at'], unique=False)
    op.create_index('ix_ai_decisions_ref', 'ai_decisions', ['ref_tipo', 'ref_id'], unique=False)
    op.create_index('ix_ai_decisions_tenant', 'ai_decisions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_tenant_id'), 'ai_decisions', ['tenant_id'], unique=False)
    op.create_index('ix_ai_decisions_tipo', 'ai_decisions', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_decisions_tipo', table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_tenant_id'), table_name='ai_decisions')
    op.drop_index('ix_ai_decisions_tenant', table_name='ai_decisions')
    op.drop_index('ix_ai_decisions_ref', table_name='ai_decisions')
    op.drop_index('ix_ai_decisions_created', table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index('ix_bm_runs_tenant', table_name='base_maestra_runs')
    op.drop_index('ix_bm_runs_fecha', table_name='base_maestra_runs')
    op.drop_index(op.f('ix_base_maestra_runs_tenant_id'), table_name='base_maestra_runs')
    op.drop_table('base_maestra_runs')
    # ### end Alembic commands ###
