"""sprint9_agentes_whatsapp_documentos

Revision ID: f87b2133aeaf
Revises: fe419dfef7c2
Create Date: 2026-05-04 08:20:00.637439
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f87b2133aeaf'
down_revision: Union[str, None] = 'fe419dfef7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes_whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=254), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('lista_precios_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('icono', sa.String(length=10), nullable=True),
    sa.Column('color_hex', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('proximo_folio', sa.Integer(), nullable=False),
    sa.Column('requires_pesos', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('system_prompt_addendum', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['lista_precios_id'], ['listas_precios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo')
    )
    op.create_index('ix_agente_cliente', 'agentes_whatsapp', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_agentes_whatsapp_tenant_id'), 'agentes_whatsapp', ['tenant_id'], unique=False)
    op.create_table('documentos_generados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('remision_id', sa.UUID(), nullable=True),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=40), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=254), nullable=False),
    sa.Column('fecha_documento', sa.Date(), nullable=True),
    sa.Column('url_storage', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes_whatsapp.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['remision_id'], ['remisiones.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_fecha', 'documentos_generados', ['fecha_documento'], unique=False)
    op.create_index('ix_doc_pedido', 'documentos_generados', ['pedido_id'], unique=False)
    op.create_index('ix_doc_remision', 'documentos_generados', ['remision_id'], unique=False)
    op.create_index('ix_doc_tipo', 'documentos_generados', ['tipo_documento'], unique=False)
    op.create_index(op.f('ix_documentos_generados_tenant_id'), 'documentos_generados', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_generados_tenant_id'), table_name='documentos_generados')
    op.drop_index('ix_doc_tipo', table_name='documentos_generados')
    op.drop_index('ix_doc_remision', table_name='documentos_generados')
    op.drop_index('ix_doc_pedido', table_name='documentos_generados')
    op.drop_index('ix_doc_fecha', table_name='documentos_generados')
    op.drop_table('documentos_generados')
    op.drop_index(op.f('ix_agentes_whatsapp_tenant_id'), table_name='agentes_whatsapp')
    op.drop_index('ix_agente_cliente', table_name='agentes_whatsapp')
    op.drop_table('agentes_whatsapp')
    # ### end Alembic commands ###
