"""sprint8_conversiones_categorias_extendidas

Revision ID: fe419dfef7c2
Revises: 00c43c0b91d0
Create Date: 2026-05-04 02:02:54.379208
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe419dfef7c2'
down_revision: Union[str, None] = '00c43c0b91d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversiones_producto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('producto_catalogado_id', sa.UUID(), nullable=False),
    sa.Column('producto_no_catalogado_id', sa.UUID(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=18, scale=6), server_default='1', nullable=False),
    sa.Column('merma_pct', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('precio_no_cat', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mezcla_grupo_id', sa.UUID(), nullable=True),
    sa.Column('mezcla_proporcion', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('prioridad', sa.Integer(), server_default='10', nullable=False),
    sa.Column('requiere_aprobacion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_catalogado_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['producto_no_catalogado_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'producto_catalogado_id', 'producto_no_catalogado_id', name='uq_conv_par')
    )
    op.create_index('ix_conv_cat', 'conversiones_producto', ['producto_catalogado_id'], unique=False)
    op.create_index('ix_conv_grupo', 'conversiones_producto', ['mezcla_grupo_id'], unique=False)
    op.create_index('ix_conv_no_cat', 'conversiones_producto', ['producto_no_catalogado_id'], unique=False)
    op.create_index(op.f('ix_conversiones_producto_tenant_id'), 'conversiones_producto', ['tenant_id'], unique=False)
    op.add_column('productos', sa.Column('categoria_extendida', sa.String(length=40), nullable=True))
    op.add_column('productos', sa.Column('es_catalogado', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('productos', sa.Column('perecedero', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('productos', sa.Column('cold_chain', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('productos', sa.Column('requiere_lote', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('productos', sa.Column('requiere_caducidad', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('productos', sa.Column('vida_util_dias', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'vida_util_dias')
    op.drop_column('productos', 'requiere_caducidad')
    op.drop_column('productos', 'requiere_lote')
    op.drop_column('productos', 'cold_chain')
    op.drop_column('productos', 'perecedero')
    op.drop_column('productos', 'es_catalogado')
    op.drop_column('productos', 'categoria_extendida')
    op.drop_index(op.f('ix_conversiones_producto_tenant_id'), table_name='conversiones_producto')
    op.drop_index('ix_conv_no_cat', table_name='conversiones_producto')
    op.drop_index('ix_conv_grupo', table_name='conversiones_producto')
    op.drop_index('ix_conv_cat', table_name='conversiones_producto')
    op.drop_table('conversiones_producto')
    # ### end Alembic commands ###
